/**
 * Cooking-content translator. Applies a 300+ entry dictionary to translate
 * recipe text (ingredients, steps, instructions) from English to Arabic
 * on the fly. Used for the TheMealDB and Forkify recipes since the upstream
 * APIs only ship English text and we cannot translate them server side.
 *
 * The Arabic is intentionally direct and modern, suitable for the general
 * home cook. Longest patterns first so phrases match before their parts.
 */

import type { Recipe, Ingredient } from '../types/recipe';

type Pair = [RegExp, string];

const TERMS: Pair[] = [
  // Units & quantities
  [/\btablespoons?\b/gi, 'ملعقة كبيرة'],
  [/\btbsps?\b/gi, 'ملعقة كبيرة'],
  [/\bteaspoons?\b/gi, 'ملعقة صغيرة'],
  [/\btsps?\b/gi, 'ملعقة صغيرة'],
  [/\bcups?\b/gi, 'كوب'],
  [/\bgrams?\b/gi, 'جرام'],
  [/\bkilograms?\b/gi, 'كيلو'],
  [/\bpounds?\b/gi, 'باوند'],
  [/\bounces?\b/gi, 'أونصة'],
  [/\b(\d+)\s*g\b/gi, '$1 جرام'],
  [/\b(\d+)\s*kg\b/gi, '$1 كيلو'],
  [/\b(\d+)\s*ml\b/gi, '$1 مل'],
  [/\b(\d+)\s*cm\b/gi, '$1 سم'],
  [/\b(\d+)°C\b/gi, '$1 درجة'],
  [/\binches?\b/gi, 'إنش'],
  [/\bminutes?\b/gi, 'دقيقة'],
  [/\bmins?\b/gi, 'دقيقة'],
  [/\bhours?\b/gi, 'ساعة'],
  [/\bhrs?\b/gi, 'ساعة'],
  [/\bseconds?\b/gi, 'ثانية'],
  [/\bdays?\b/gi, 'يوم'],
  [/\bservings?\b/gi, 'حصّة'],

  // Cooking actions
  [/\bpreheat the oven\b/gi, 'سخن الفرن'],
  [/\bpreheat oven\b/gi, 'سخن الفرن'],
  [/\bbring to a boil\b/gi, 'اغلِ على نار قوية'],
  [/\bbring to a simmer\b/gi, 'اغلِ على نار هادئة'],
  [/\bsimmer\b/gi, 'اغلِ على نار هادئة'],
  [/\bboil\b/gi, 'اسلق'],
  [/\bcover\b/gi, 'غطِّ'],
  [/\buncover\b/gi, 'اكشف الغطاء'],
  [/\bstir\b/gi, 'قلّب'],
  [/\btoss\b/gi, 'قلّب'],
  [/\bwhisk\b/gi, 'اخفق'],
  [/\bbeat\b/gi, 'اخفق'],
  [/\bmix\b/gi, 'اخلط'],
  [/\bcombine\b/gi, 'امزج'],
  [/\bblend\b/gi, 'اخلط في الخلاط'],
  [/\bknead\b/gi, 'اعجن'],
  [/\broll\b/gi, 'لفّ'],
  [/\bchop\b/gi, 'قطّع'],
  [/\bdice\b/gi, 'قطّع مكعبات'],
  [/\bslice\b/gi, 'قطّع شرائح'],
  [/\bmince\b/gi, 'افرم ناعم'],
  [/\bgrate\b/gi, 'ابشر'],
  [/\bmash\b/gi, 'اهرس'],
  [/\bcrush\b/gi, 'اهرس'],
  [/\bsprinkle\b/gi, 'رشّ'],
  [/\bdrizzle\b/gi, 'رشّ'],
  [/\bpour\b/gi, 'اسكب'],
  [/\badd\b/gi, 'أضف'],
  [/\bremove\b/gi, 'ارفع'],
  [/\bdrain\b/gi, 'صفِّ'],
  [/\brinse\b/gi, 'اشطف'],
  [/\bsoak\b/gi, 'انقع'],
  [/\bheat\b/gi, 'سخن'],
  [/\bcook\b/gi, 'اطبخ'],
  [/\bbake\b/gi, 'اخبز'],
  [/\bgrill\b/gi, 'اشوِ'],
  [/\broast\b/gi, 'حمّر بالفرن'],
  [/\bfry\b/gi, 'اقلِ'],
  [/\bdeep[-\s]?fry\b/gi, 'اقلِ في زيت غزير'],
  [/\bbrown\b/gi, 'حمّر'],
  [/\bsear\b/gi, 'حمّر بسرعة'],
  [/\bsaut(é|e)\b/gi, 'قلّب على نار قوية'],
  [/\bsteam\b/gi, 'بخّر'],
  [/\bserve\b/gi, 'قدّم'],
  [/\bgarnish\b/gi, 'زيّن'],
  [/\bcool\b/gi, 'برّد'],
  [/\bchill\b/gi, 'برّد في الثلاجة'],
  [/\brefrigerate\b/gi, 'ضع في الثلاجة'],
  [/\bmelt\b/gi, 'اذوّب'],
  [/\btoast\b/gi, 'حمّص'],
  [/\bseason\b/gi, 'تبّل'],
  [/\btaste\b/gi, 'تذوّق'],
  [/\bcheck\b/gi, 'افحص'],
  [/\bset aside\b/gi, 'ضع جانباً'],
  [/\bplace\b/gi, 'ضع'],
  [/\blift\b/gi, 'ارفع'],
  [/\breturn\b/gi, 'أعد'],
  [/\brepeat\b/gi, 'كرّر'],
  [/\bfold\b/gi, 'اطوِ'],
  [/\bsqueeze\b/gi, 'اعصر'],
  [/\bcrumble\b/gi, 'فتّت'],
  [/\bspread\b/gi, 'افرد'],
  [/\bpress\b/gi, 'اضغط'],
  [/\binvert\b/gi, 'اقلب'],
  [/\btransfer\b/gi, 'انقل'],
  [/\barrange\b/gi, 'رتّب'],
  [/\bpile\b/gi, 'كوّم'],
  [/\bdrop\b/gi, 'أسقط'],
  [/\btrim\b/gi, 'قصّ'],
  [/\bpeel\b/gi, 'قشّر'],
  [/\bcrack\b/gi, 'اكسر'],
  [/\bsift\b/gi, 'انخل'],
  [/\bbrush\b/gi, 'ادهن'],

  // Oils & fats
  [/\bolive oil\b/gi, 'زيت زيتون'],
  [/\bvegetable oil\b/gi, 'زيت نباتي'],
  [/\bsesame oil\b/gi, 'زيت سمسم'],
  [/\bsunflower oil\b/gi, 'زيت دوّار الشمس'],
  [/\bbutter\b/gi, 'زبدة'],
  [/\bghee\b/gi, 'سمنة'],
  [/\bsmen\b/gi, 'سمنة بلدية'],
  [/\bcoconut oil\b/gi, 'زيت جوز الهند'],

  // Salt, pepper, basics
  [/\bblack pepper\b/gi, 'فلفل أسود'],
  [/\bwhite pepper\b/gi, 'فلفل أبيض'],
  [/\bsalt\b/gi, 'ملح'],
  [/\bpepper\b/gi, 'فلفل'],

  // Aromatics
  [/\bgarlic cloves?\b/gi, 'فص ثوم'],
  [/\bgarlic\b/gi, 'ثوم'],
  [/\bshallots?\b/gi, 'بصل صغير'],
  [/\bonions?\b/gi, 'بصل'],
  [/\bginger\b/gi, 'زنجبيل'],
  [/\bscallions?\b/gi, 'بصل أخضر'],
  [/\bgreen onions?\b/gi, 'بصل أخضر'],
  [/\bspring onions?\b/gi, 'بصل أخضر'],

  // Spices & herbs
  [/\bcumin\b/gi, 'كمّون'],
  [/\bcoriander\b/gi, 'كزبرة'],
  [/\bcilantro\b/gi, 'كزبرة'],
  [/\bparsley\b/gi, 'بقدونس'],
  [/\bmint\b/gi, 'نعنع'],
  [/\bbasil\b/gi, 'ريحان'],
  [/\bdill\b/gi, 'شبت'],
  [/\bchives\b/gi, 'ثوم معمّر'],
  [/\bbay leaves?\b/gi, 'ورق غار'],
  [/\bbay leaf\b/gi, 'ورق غار'],
  [/\bcinnamon\b/gi, 'قرفة'],
  [/\bcardamom\b/gi, 'هيل'],
  [/\bcloves?\b/gi, 'قرنفل'],
  [/\ballspice\b/gi, 'بهار حلو'],
  [/\bsaffron\b/gi, 'زعفران'],
  [/\bturmeric\b/gi, 'كركم'],
  [/\bpaprika\b/gi, 'بابريكا'],
  [/\bsmoked paprika\b/gi, 'بابريكا مدخّنة'],
  [/\boregano\b/gi, 'زعتر بري'],
  [/\bthyme\b/gi, 'زعتر'],
  [/\brosemary\b/gi, 'إكليل الجبل'],
  [/\bnutmeg\b/gi, 'جوزة الطيب'],
  [/\bsumac\b/gi, 'سمّاق'],
  [/\bza['']?atar\b/gi, 'زعتر'],
  [/\bbaharat\b/gi, 'بهار مشكّل'],
  [/\bras el hanout\b/gi, 'رأس الحانوت'],
  [/\bharissa\b/gi, 'هريسة'],
  [/\bmahlab\b/gi, 'محلب'],
  [/\bdried lime\b/gi, 'لومي'],
  [/\bloomi\b/gi, 'لومي'],
  [/\bfenugreek\b/gi, 'حلبة'],
  [/\bcaraway\b/gi, 'كراويا'],
  [/\bchili powder\b/gi, 'بودرة شطّة'],
  [/\bchili flakes\b/gi, 'فلفل حار مجروش'],
  [/\bred pepper flakes\b/gi, 'فلفل حار مجروش'],
  [/\bchile\b/gi, 'فلفل حار'],
  [/\bchili\b/gi, 'فلفل حار'],

  // Vegetables
  [/\bcherry tomatoes?\b/gi, 'طماطم كرزية'],
  [/\btomatoes?\b/gi, 'طماطم'],
  [/\bpotatoes?\b/gi, 'بطاطا'],
  [/\bpotato\b/gi, 'بطاطا'],
  [/\bsweet potato\b/gi, 'بطاطا حلوة'],
  [/\bcarrots?\b/gi, 'جزر'],
  [/\bcelery stalks?\b/gi, 'كرفس'],
  [/\bcelery\b/gi, 'كرفس'],
  [/\bbell peppers?\b/gi, 'فلفل ألوان'],
  [/\bpeppers?\b/gi, 'فلفل'],
  [/\beggplants?\b/gi, 'باذنجان'],
  [/\baubergines?\b/gi, 'باذنجان'],
  [/\bzucchini\b/gi, 'كوسا'],
  [/\bcourgettes?\b/gi, 'كوسا'],
  [/\bcucumbers?\b/gi, 'خيار'],
  [/\bspinach\b/gi, 'سبانخ'],
  [/\bcabbage\b/gi, 'كرنب'],
  [/\blettuce\b/gi, 'خس'],
  [/\bokra\b/gi, 'بامية'],
  [/\bgreen beans?\b/gi, 'فاصوليا خضراء'],
  [/\bpeas\b/gi, 'بازلاء'],
  [/\bcorn kernels?\b/gi, 'حبّات ذرة'],
  [/\bcorn\b/gi, 'ذرة'],
  [/\bmushrooms?\b/gi, 'مشروم'],
  [/\basparagus\b/gi, 'هليون'],
  [/\bcauliflower\b/gi, 'قرنبيط'],
  [/\bbroccoli\b/gi, 'بروكلي'],
  [/\bgrape leaves?\b/gi, 'ورق عنب'],
  [/\bvine leaves?\b/gi, 'ورق عنب'],
  [/\bavocado\b/gi, 'أفوكادو'],
  [/\bbeetroot\b/gi, 'شمندر'],
  [/\bbeets?\b/gi, 'شمندر'],
  [/\bartichokes?\b/gi, 'خرشوف'],
  [/\bbrussels sprouts\b/gi, 'كرنب بروكسل'],

  // Proteins
  [/\bground lamb\b/gi, 'لحم خروف مفروم'],
  [/\bground beef\b/gi, 'لحم بقر مفروم'],
  [/\bground turkey\b/gi, 'ديك رومي مفروم'],
  [/\bground meat\b/gi, 'لحم مفروم'],
  [/\blamb shanks?\b/gi, 'موزة خروف'],
  [/\blamb shoulder\b/gi, 'كتف خروف'],
  [/\blamb\b/gi, 'لحم خروف'],
  [/\bmutton\b/gi, 'لحم ضأن'],
  [/\bbeef\b/gi, 'لحم بقر'],
  [/\bchicken thighs?\b/gi, 'أفخاذ دجاج'],
  [/\bchicken breasts?\b/gi, 'صدر دجاج'],
  [/\bchicken\b/gi, 'دجاج'],
  [/\bsalmon\b/gi, 'سلمون'],
  [/\btuna\b/gi, 'تونة'],
  [/\bcod\b/gi, 'سمك القد'],
  [/\bshrimp\b/gi, 'روبيان'],
  [/\bprawns?\b/gi, 'روبيان'],
  [/\bfish\b/gi, 'سمك'],
  [/\beggs?\b/gi, 'بيض'],
  [/\bturkey\b/gi, 'ديك رومي'],
  [/\bsausages?\b/gi, 'سجق'],
  [/\bbacon\b/gi, 'بيكون'],
  [/\bbone[-\s]?in\b/gi, 'بعظمه'],
  [/\bboneless\b/gi, 'بدون عظم'],

  // Dairy
  [/\bgreek yogurt\b/gi, 'لبن يوناني'],
  [/\byogurt\b/gi, 'لبن'],
  [/\bmilk\b/gi, 'حليب'],
  [/\bheavy cream\b/gi, 'قشطة سائلة'],
  [/\bsour cream\b/gi, 'لبن حامض'],
  [/\bcream\b/gi, 'كريمة'],
  [/\bcheese\b/gi, 'جبنة'],
  [/\bmozzarella\b/gi, 'موزاريلا'],
  [/\bparmesan\b/gi, 'بارميزان'],
  [/\bfeta\b/gi, 'فيتا'],
  [/\bricotta\b/gi, 'ريكوتا'],
  [/\bhalloumi\b/gi, 'حلوم'],
  [/\bjameed\b/gi, 'جميد'],
  [/\bbuttermilk\b/gi, 'لبن خثره'],

  // Grains & legumes
  [/\bbasmati rice\b/gi, 'أرز بسمتي'],
  [/\bjasmine rice\b/gi, 'أرز ياسمين'],
  [/\bbrown rice\b/gi, 'أرز بني'],
  [/\bwhite rice\b/gi, 'أرز أبيض'],
  [/\blong[-\s]?grain rice\b/gi, 'أرز طويل الحبة'],
  [/\bshort[-\s]?grain rice\b/gi, 'أرز قصير الحبة'],
  [/\brice\b/gi, 'أرز'],
  [/\bbulgur\b/gi, 'برغل'],
  [/\bcouscous\b/gi, 'كسكس'],
  [/\bquinoa\b/gi, 'كينوا'],
  [/\boats?\b/gi, 'شوفان'],
  [/\bwheat\b/gi, 'قمح'],
  [/\bsemolina\b/gi, 'سميد'],
  [/\bwhole wheat flour\b/gi, 'دقيق قمح كامل'],
  [/\ball[-\s]?purpose flour\b/gi, 'دقيق متعدد الاستخدامات'],
  [/\bflour\b/gi, 'دقيق'],
  [/\bcornmeal\b/gi, 'دقيق ذرة'],
  [/\bcornstarch\b/gi, 'نشا'],
  [/\bvermicelli\b/gi, 'شعيرية'],
  [/\bspaghetti\b/gi, 'سباغيتي'],
  [/\bfettuccine\b/gi, 'فيتوتشيني'],
  [/\bpenne\b/gi, 'بيني'],
  [/\bnoodles\b/gi, 'نودلز'],
  [/\bpasta\b/gi, 'باستا'],
  [/\bred lentils?\b/gi, 'عدس أحمر'],
  [/\bgreen lentils?\b/gi, 'عدس أخضر'],
  [/\blentils?\b/gi, 'عدس'],
  [/\bchickpeas?\b/gi, 'حمّص'],
  [/\bblack beans?\b/gi, 'فاصوليا سوداء'],
  [/\bkidney beans?\b/gi, 'فاصوليا حمراء'],
  [/\bnavy beans?\b/gi, 'فاصوليا بيضاء'],
  [/\bfava beans?\b/gi, 'فول'],
  [/\bbeans?\b/gi, 'فاصوليا'],

  // Pantry
  [/\bbrown sugar\b/gi, 'سكر بني'],
  [/\bsugar\b/gi, 'سكر'],
  [/\bhoney\b/gi, 'عسل'],
  [/\bmolasses\b/gi, 'دبس'],
  [/\bpomegranate molasses\b/gi, 'دبس رمان'],
  [/\bdate syrup\b/gi, 'دبس تمر'],
  [/\bmaple syrup\b/gi, 'شراب القيقب'],
  [/\bbalsamic vinegar\b/gi, 'خل بلسمي'],
  [/\bwhite vinegar\b/gi, 'خل أبيض'],
  [/\brice vinegar\b/gi, 'خل أرز'],
  [/\bapple cider vinegar\b/gi, 'خل تفاح'],
  [/\bvinegar\b/gi, 'خل'],
  [/\bsoy sauce\b/gi, 'صلصة الصويا'],
  [/\bfish sauce\b/gi, 'صلصة السمك'],
  [/\boyster sauce\b/gi, 'صلصة المحار'],
  [/\btahini\b/gi, 'طحينة'],
  [/\bdijon mustard\b/gi, 'خردل ديجون'],
  [/\bmustard\b/gi, 'خردل'],
  [/\bmayonnaise\b/gi, 'مايونيز'],
  [/\bworcestershire sauce\b/gi, 'صلصة ووستر'],
  [/\bketchup\b/gi, 'كاتشب'],
  [/\btomato paste\b/gi, 'صلصة طماطم'],
  [/\btomato sauce\b/gi, 'صلصة طماطم'],
  [/\bmarinara\b/gi, 'صلصة طماطم'],
  [/\bchicken broth\b/gi, 'مرق دجاج'],
  [/\bchicken stock\b/gi, 'مرق دجاج'],
  [/\bvegetable broth\b/gi, 'مرق خضار'],
  [/\bvegetable stock\b/gi, 'مرق خضار'],
  [/\bbeef broth\b/gi, 'مرق لحم'],
  [/\bbeef stock\b/gi, 'مرق لحم'],
  [/\bstock\b/gi, 'مرق'],
  [/\bbroth\b/gi, 'مرق'],

  // Fruits & nuts
  [/\blemon juice\b/gi, 'عصير ليمون'],
  [/\blemons?\b/gi, 'ليمون'],
  [/\blimes?\b/gi, 'ليمون أخضر'],
  [/\boranges?\b/gi, 'برتقال'],
  [/\borange blossom water\b/gi, 'ماء زهر'],
  [/\brose water\b/gi, 'ماء ورد'],
  [/\bdates?\b/gi, 'تمر'],
  [/\braisins?\b/gi, 'زبيب'],
  [/\bapples?\b/gi, 'تفاح'],
  [/\bbananas?\b/gi, 'موز'],
  [/\bberries\b/gi, 'توت'],
  [/\bblueberries\b/gi, 'توت أزرق'],
  [/\bstrawberries\b/gi, 'فراولة'],
  [/\bpineapples?\b/gi, 'أناناس'],
  [/\bmangoes?\b/gi, 'مانجو'],
  [/\bpomegranates?\b/gi, 'رمان'],
  [/\balmonds?\b/gi, 'لوز'],
  [/\bwalnuts?\b/gi, 'جوز'],
  [/\bpistachios?\b/gi, 'فستق'],
  [/\bpine nuts?\b/gi, 'صنوبر'],
  [/\bcashews?\b/gi, 'كاجو'],
  [/\bsesame seeds\b/gi, 'سمسم'],
  [/\bsesame\b/gi, 'سمسم'],
  [/\bsunflower seeds\b/gi, 'بذور دوّار الشمس'],

  // Bread/dough
  [/\bpita bread\b/gi, 'خبز بيتا'],
  [/\bpita\b/gi, 'بيتا'],
  [/\bphyllo\b/gi, 'عجينة فيلو'],
  [/\bfilo\b/gi, 'فيلو'],
  [/\bkataifi\b/gi, 'كتايف'],
  [/\bbread\b/gi, 'خبز'],
  [/\bdough\b/gi, 'عجين'],
  [/\byeast\b/gi, 'خميرة'],
  [/\bbaking powder\b/gi, 'بيكنغ بودر'],
  [/\bbaking soda\b/gi, 'صودا الخبز'],
  [/\btortillas?\b/gi, 'تورتيا'],

  // Liquids
  [/\bhot water\b/gi, 'ماء ساخن'],
  [/\bwarm water\b/gi, 'ماء دافئ'],
  [/\bcold water\b/gi, 'ماء بارد'],
  [/\bice water\b/gi, 'ماء مثلج'],
  [/\bwater\b/gi, 'ماء'],
  [/\bwhite wine\b/gi, 'خل أبيض'],
  [/\bred wine\b/gi, 'خل أحمر'],
  [/\bwine\b/gi, 'خل'],
  [/\bbeer\b/gi, 'ماء غازي'],

  // Modifiers
  [/\bdried\b/gi, 'مجفّف'],
  [/\bfresh\b/gi, 'طازج'],
  [/\bfrozen\b/gi, 'مجمّد'],
  [/\bcanned\b/gi, 'معلّب'],
  [/\bsoftened\b/gi, 'لينة'],
  [/\bmelted\b/gi, 'مذوّبة'],
  [/\bchopped\b/gi, 'مقطّع'],
  [/\bminced\b/gi, 'مفروم'],
  [/\bsliced\b/gi, 'شرائح'],
  [/\bgrated\b/gi, 'مبشور'],
  [/\bground\b/gi, 'مطحون'],
  [/\bwhole\b/gi, 'كاملة'],
  [/\bhalved\b/gi, 'نصفين'],
  [/\bquartered\b/gi, 'أرباع'],
  [/\bcrushed\b/gi, 'مهروسة'],
  [/\btoasted\b/gi, 'محمّصة'],
  [/\bsmall\b/gi, 'صغير'],
  [/\bmedium\b/gi, 'متوسّط'],
  [/\blarge\b/gi, 'كبير'],
  [/\bthick\b/gi, 'سميك'],
  [/\bthin\b/gi, 'رقيق'],
  [/\bsweet\b/gi, 'حلو'],
  [/\bsour\b/gi, 'حامض'],
  [/\bspicy\b/gi, 'حار'],
  [/\bhot\b/gi, 'حار'],
  [/\bcold\b/gi, 'بارد'],
  [/\bwarm\b/gi, 'دافئ'],
  [/\bsoft\b/gi, 'طري'],
  [/\bhard\b/gi, 'قاسٍ'],
  [/\bcrispy\b/gi, 'مقرمش'],
  [/\btender\b/gi, 'طري'],
  [/\bgolden brown\b/gi, 'ذهبي'],
  [/\bgolden\b/gi, 'ذهبي'],
  [/\bcaramelized\b/gi, 'مكرمل'],
  [/\bextra[-\s]?virgin\b/gi, 'بكر ممتاز'],

  // Common phrases (these last since they include shorter words)
  [/\bover medium[-\s]?low heat\b/gi, 'على نار هادئة'],
  [/\bover medium[-\s]?high heat\b/gi, 'على نار قوية'],
  [/\bover medium heat\b/gi, 'على نار متوسطة'],
  [/\bover high heat\b/gi, 'على نار قوية'],
  [/\bover low heat\b/gi, 'على نار هادئة'],
  [/\bin a large pan\b/gi, 'في مقلاة كبيرة'],
  [/\bin a pan\b/gi, 'في مقلاة'],
  [/\bin a pot\b/gi, 'في قدر'],
  [/\bin a bowl\b/gi, 'في وعاء'],
  [/\bin the oven\b/gi, 'في الفرن'],
  [/\buntil\b/gi, 'حتى'],
  [/\babout\b/gi, 'حوالي'],
  [/\bapproximately\b/gi, 'حوالي'],
  [/\boptional\b/gi, 'اختياري'],
  [/\bto serve\b/gi, 'للتقديم'],
  [/\bto taste\b/gi, 'حسب الرغبة'],
  [/\bto garnish\b/gi, 'للتزيين'],
];


export function translateRecipeText(text: string): string {
  if (!text) return '';
  let result = text;
  for (const [pattern, replacement] of TERMS) {
    result = result.replace(pattern, replacement);
  }
  return result.replace(/\s+/g, ' ').trim();
}


function translateIngredient(ing: Ingredient): Ingredient {
  return {
    name: translateRecipeText(ing.name),
    measure: ing.measure, // measures are mostly numeric, keep as-is
    original: translateRecipeText(ing.original),
  };
}


/**
 * Returns a new Recipe with text fields translated to Arabic. Title is left
 * alone (most TheMealDB titles are food names like "Beef Stew" that read fine
 * for cooks even in Arabic mode). The fields the home cook actually needs to
 * follow (ingredients, steps, instructions) are translated.
 */
export function translateRecipe(r: Recipe): Recipe {
  return {
    ...r,
    instructions: r.instructions ? translateRecipeText(r.instructions) : r.instructions,
    steps: r.steps ? r.steps.map(translateRecipeText) : r.steps,
    ingredients: r.ingredients ? r.ingredients.map(translateIngredient) : r.ingredients,
    tags: r.tags ? r.tags.map(translateRecipeText) : r.tags,
  };
}
